version: "3"

services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    ports:
     - "3306:3306"
    volumes:
     - ./volumes/mysql/data:/var/lib/mysql
     - ./volumes/mysql:/docker-entrypoint-initdb.d/:ro
    environment:
     - MYSQL_ROOT_PASSWORD=root
  grafana:
    container_name: grafana_container
    image: grafana/grafana:6.5.0
    ports:
      - 3000:3000
    user: '1000:1000'
    volumes:
      - ./volumes/grafana:/var/lib/grafana
  node-red:
    container_name: nodered_container
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./volumes/node-red:/data
